type Course {
  _id: String!
  title: String
  description: String
  price: String
  image: String
}
type Query {
  courses: [Course]
  getCourseById(_id: String): Course
}

type Mutation {
  getCourse(_id: String): Course!
  addCourse(
    title: String
    description: String
    price: String
    image: String
  ): Course!
  updateCourse(
    _id: String
    title: String
    description: String
    price: String
    image: String
  ): Course!
  removeCourse(_id: String!): Course!
}
